const PDFDocument = require('pdfkit');

const generateReport = (websiteUrl, issues, scanDate) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text('Complyzo Scan Report', { align: 'center' });
      doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`Website: ${websiteUrl}`, { align: 'center' })
        .text(`Date: ${new Date(scanDate).toLocaleDateString()}`, { align: 'center' });
      
      doc.moveDown(1);
      
      // Summary
      const criticalCount = issues.filter(i => i.severity === 'Critical').length;
      const warningCount = issues.filter(i => i.severity === 'Warning').length;
      
      doc.fontSize(14).fillColor('#000').text('Summary', { underline: true });
      doc.fontSize(11)
        .text(`Total Issues: ${issues.length}`)
        .text(`Critical: ${criticalCount}`)
        .text(`Warnings: ${warningCount}`);
      
      doc.moveDown(1);
      
      // Issues Table
      doc.fontSize(14).text('Issues Found', { underline: true });
      doc.moveDown(0.5);
      
      issues.forEach((issue, i) => {
        const color = issue.severity === 'Critical' ? '#DC2626' : '#D97706';
        doc.fontSize(10).fillColor(color).font('Helvetica-Bold')
          .text(`${i + 1}. [${issue.severity}] ${issue.message}`);
      });
      
      doc.moveDown(1);
      
      // Footer
      doc.fontSize(8).fillColor('#999').font('Helvetica')
        .text('Generated by Complyzo - AI Website Monitor', { align: 'center' })
        .text('https://getcomplyzo.com', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = generateReport;